### ISSUE TITLE
Location: Superbunny Cave 

### ISSUE THREAD

**Issue by docuhorror** [arborelia/alttpr#2]
> Superbunny Cave: the Dark World equivalent of Paradox Cave, so named because you can open the chests as a bunny if you come in from the top
not a huge deal seeing as you very rarely get these chests without moon pearl, and imo this is more about Where this location is but: you need to come in from the bottom, so you can fall through the hole and activate the glitch. coming in from the top doesnt let you get the chests.

**Comment by rspeer** [comment]
Good point, thanks. Fixed now.
